### ISSUE TITLE
[log]2024/03/08

### ISSUE THREAD

**Issue by borntoolate** [borntoolate/tasukete#24]
_Not everything can be written freely._
[Issues](https://github.com/borntoolate/tasukete/issues)

**Comment by borntoolate** [comment]
Reactなのでポモドーロの5分休憩中にReact Forgetの記事読んだら作業何やってたか全部忘れちゃった
https://zenn.dev/terass_dev/articles/6f49e44d9cfb0d

**Comment by borntoolate** [comment]
もっと言ってほしい
https://zenn.dev/ficilcom/articles/not-need-aws

**Comment by borntoolate** [comment]
[覚えられない]スクロールバーのカスタマイズは普通のcssで絶対なんとかなってほしいと祈りながら書くもの

```css
      overflow-x: auto;

      &::-webkit-scrollbar {
        width: 4px;
      }

      &::-webkit-scrollbar-track {
        background-color: transparent;
      }

      &::-webkit-scrollbar-thumb {
        background-color: rgba(var(--color-gray-dark) / 100%);
      }

      scrollbar-width: thin;
      scrollbar-color: rgba(var(--color-gray-dark) / 100%) transparent;
```
